In [1]:
import numpy  as np
a=np.arange(9)
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(5,3,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [10]:
np.identity(9,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
new_a=a.reshape(9,1)
new_a


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [20]:
ar2=np.arange(16).reshape(4,4)
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
ar2[0:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
ar2[3:4]

array([[12, 13, 14, 15]])

In [30]:
ar2[-3:,-3:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [31]:
ar2[-3:-1,-3:-1]

array([[ 5,  6],
       [ 9, 10]])

In [40]:
ar3=np.arange(50).reshape(5,10)

In [41]:
ar3


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [43]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [44]:
# linspace()
np.linspace(1,10,2)

array([ 1., 10.])

In [49]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [50]:
np.linspace(1,10,5,dtype=float)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [51]:
np.linspace(1,10,5,dtype=complex)

array([ 1.  +0.j,  3.25+0.j,  5.5 +0.j,  7.75+0.j, 10.  +0.j])

In [52]:
np.linspace(1,10,5,retstep=True)

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)

In [57]:
# random modules
# To generate random numbers between the range
# np.random.randint(start,end)
np.random.randint(1234,100000)

91513

In [58]:
np.random.randint(1234,100000,2)

array([11972, 24780])

In [59]:
np.random.randint(1234,100000,20)

array([78616, 50434, 88492, 77497,  5378,  4024, 39017, 98117, 68269,
        2897, 62468, 33745, 38810, 11997, 56037, 92912, 22384, 16659,
       30710, 93212])

In [67]:
# Uniform Distrubution
# here in bulid generate the values from 0 t0 1 values
np.random.rand(2)

array([0.86994079, 0.94892811])

In [70]:
# Normalised Distrubution/
# here generate the values from  -1 to 1
np.random.randn(12)

array([ 1.00713328,  0.665814  ,  0.90268964,  0.61218816,  1.11821107,
        0.03982411, -0.79306452,  0.66196694,  0.04122267, -1.27220667,
        1.62053698, -0.53558092])

In [69]:
np.random.randn(2)

array([-0.36448085,  0.42492253])

In [74]:
a.max()

8

In [76]:
ar2.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [77]:
ar2.max()

15

In [78]:
ar2.min()

0

In [3]:
import pandas as pd

In [10]:
my=[109.9]
pd.Series(my)

0    109.9
dtype: float64

In [33]:
ser1=pd.Series([1,2,3,4],["Mohan(cr)","Raja(The topper)","Madhan(coder)","sai"])
ser1

Mohan(cr)           1
Raja(The topper)    2
Madhan(coder)       3
sai                 4
dtype: int64

In [18]:
ser1[0:3]

Mohan(cr)           1
Raja(The topper)    2
Madhan(coder)       3
dtype: int64

In [32]:
ser2=pd.Series([1,2,3,4],['sss','ww','qq','fjh'])
ser3=ser1+ser2
ser3

Madhan(coder)      NaN
Mohan(cr)          NaN
Raja(The topper)   NaN
fjh                NaN
qq                 NaN
sai(all rounder)   NaN
sss                NaN
ww                 NaN
dtype: float64

In [35]:
ser1.drop('sai')

Mohan(cr)           1
Raja(The topper)    2
Madhan(coder)       3
dtype: int64

In [36]:
# DataFrame
# pd.DataFrame(datas,row_label,col_label)

In [38]:
df=pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -1.928635  0.546998  1.033316  1.097996
1  1.679046  0.615670 -1.578520  1.123289
2  0.026274  1.869523  0.377245  0.360294
3 -0.131066 -0.402512  0.605590  2.143724
4  1.176166  0.196527  0.689768 -2.810037

In [77]:
# to convert dictionary into dataframe
d={"col1":[11,22,33],"col2":[10,20,3],"col3":[55,66.4]}
d

{'col1': [11, 22, 33], 'col2': [10, 20, 3], 'col3': [55, 66.4]}

In [52]:
df=pd.DataFrame(data=d)
df

co1  col2  col3
0   11    10    55
1   22    20    66

In [49]:
df=pd.DataFrame(d,["row1","row2"])

In [50]:
df

co1  col2  col3
row1    1     1     5
row2    2     2     6

In [53]:
df.T

0   1
co1   11  22
col2  10  20
col3  55  66

In [56]:
df.columns

Index(['co1', 'col2', 'col3'], dtype='object')

In [57]:
type(df)

pandas.core.frame.DataFrame

In [61]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [62]:
df.dtypes

co1     int64
col2    int64
col3    int64
dtype: object

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   co1     2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 180.0 bytes


In [65]:
df.values

array([[11, 10, 55],
       [22, 20, 66]], dtype=int64)

In [66]:
df.axes

[RangeIndex(start=0, stop=2, step=1),
 Index(['co1', 'col2', 'col3'], dtype='object')]

In [67]:
df.size

6

In [68]:
df.ndim

2

In [74]:
# to access multiple columns
df[['co1','col2']]

co1  col2
0   11    10
1   22    20

In [75]:
# to access column
df[['co1']]

co1
0   11
1   22

In [81]:
# To create new column
df['new']=df['co1']+df['col2']
df

co1  col2  col3  new
0   11    10    55   21
1   22    20    66   42

In [89]:
# To delete colum{Actually is will not delete see next opertion---> is use the inplace opertion}
df.drop('co1',axis=1)

In [83]:
df


co1  col2  col3  new
0   11    10    55   21
1   22    20    66   42

In [84]:
df.drop('co1',axis=1,inplace=True)

In [85]:
df

col2  col3  new
0    10    55   21
1    20    66   42

In [86]:
df

col2  col3  new
0    10    55   21
1    20    66   42